# Generated by Django 3.0.2 on 2020-02-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20200225_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='owner_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
